name: alert_button
description: A Flutter package that provides a customizable alert button with animated wave effects.
version: 0.0.1
homepage: https://github.com/your_username/alert_button
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
